### ISSUE TITLE
URL in GitHub is wrong

### ISSUE THREAD

**Issue by TheAlexLichter** [antfu/slidev-new#1]
Hey! Just a heads up that the URL set in the settings of the repo isn't correct.

![grafik](https://user-images.githubusercontent.com/640208/159734367-45e04ac9-fd88-47dc-9d49-09d89534334b.png)

**Comment by TheAlexLichter** [comment]
cc @antfu

**Comment by antfu** [comment]
Oh it took me 5mins to understand where it is 😅 Fixed
