### ISSUE TITLE
# Slidev で URL から Markdown ファイルを開けない

### ISSUE THREAD

**Issue by M-Yuu23586** [antfu/slidev-new#2]
## 概要
SlidevでURLを指定してMarkdownファイルを開こうとしましたが、正しく動作しませんでした。ローカルファイル（`slides.md`）を問題なく開ける一方で、外部URLから指定されたファイルを直接開くことができないようです。
この問題を修正してくれると助かります。

## 再現手順
1. Slidevをインストールします。
2. 以下のコマンドでURLからMarkdownファイルを開こうとします。
   ```bash
   slidev https://example.com/slides.md
   ```
- Node.jsバージョン: v20.18.0
- npmバージョン: 10.8.2
- Slidevバージョン: 0.50.0-beta.4
- OS: macOS (15.0.1 [ID: 24A348])

### Reproduction

Versionはこんな感じ

### System Info

```Shell
matsumurayuu@M-Yuu-Mac ~ %    node -v
v20.18.0
matsumurayuu@M-Yuu-Mac ~ % 
matsumurayuu@M-Yuu-Mac ~ %    npm -v
10.8.2
matsumurayuu@M-Yuu-Mac ~ % 
matsumurayuu@M-Yuu-Mac ~ %    slidev -v
0.50.0-beta.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Slidev is not designed to work that way. Supporting files from a URL would introduce a lot of other problems, such as asset handling or theme/components loading. Consider you can't change the content when it's on a URL, I don't think this feature would be generally useful and do not worth the effort. Please use Slidev locally.
